### PR TITLE
Update doxygen to v1.8.18

### PR DESCRIPTION
**Pull request by Simran-B**
Doxygen 1.8.18 was released on April 13th 2020:
https://sourceforge.net/projects/doxygen/files/

### CODE REVIEW

**Comment by mlt** [comment]
Thanks!

**Comment by mlt** [comment]
Oops... I forgot I use AU, now I need to force the build as it thinks we are already on 1.8.18 :(

**Comment by Simran-B** [comment]
@mlt Doxygen 1.8.20 is out, i.e. an opportunity to reinstate AU.

**Comment by mlt** [comment]
Thanks for the reminder! Let's do it right this time. I submitted a request for [scheduled builds](https://www.appveyor.com/blog/2017/11/08/sheduled-builds-for-free-accounts/).

**Pull request merged**
